/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airline_reservation_system;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author GuestAccount
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MinWindow
     */
    Login_window login;
    public MainWindow() {
        initComponents();
        login=new Login_window();
        Desktop.add(login);
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        customer = new javax.swing.JMenu();
        add_customer = new javax.swing.JMenuItem();
        search_customer = new javax.swing.JMenuItem();
        tickets = new javax.swing.JMenu();
        add_flights = new javax.swing.JMenuItem();
        book_ticket = new javax.swing.JMenuItem();
        report = new javax.swing.JMenuItem();
        user = new javax.swing.JMenu();
        create_account = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );

        customer.setText("Customer");

        add_customer.setText("Add Customer");
        add_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_customerActionPerformed(evt);
            }
        });
        customer.add(add_customer);

        search_customer.setText("Search Customer");
        search_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_customerActionPerformed(evt);
            }
        });
        customer.add(search_customer);

        jMenuBar1.add(customer);

        tickets.setText("Tickets");

        add_flights.setText("Add Flight");
        add_flights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_flightsActionPerformed(evt);
            }
        });
        tickets.add(add_flights);

        book_ticket.setText("Book Ticket");
        book_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_ticketActionPerformed(evt);
            }
        });
        tickets.add(book_ticket);

        report.setText("Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        tickets.add(report);

        jMenuBar1.add(tickets);

        user.setText("User");

        create_account.setText("Create Account");
        create_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_accountActionPerformed(evt);
            }
        });
        user.add(create_account);

        jMenuBar1.add(user);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_customerActionPerformed
        // TODO add your handling code here:
        Add_customer customer = null;
        try {
            customer = new Add_customer();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        Desktop.add(customer);
        customer.setVisible(true);
    }//GEN-LAST:event_add_customerActionPerformed

    private void search_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_customerActionPerformed
        // TODO add your handling code here:
        Search search=new Search();
        Desktop.add(search);
        search.setVisible(true);
    }//GEN-LAST:event_search_customerActionPerformed

    private void add_flightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_flightsActionPerformed
        // TODO add your handling code here:
        add_flights flights=new add_flights();
        Desktop.add(flights);
        flights.setVisible(true);        
    }//GEN-LAST:event_add_flightsActionPerformed

    private void book_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_ticketActionPerformed
        // TODO add your handling code here:
        Book_tickets tickets = null;  
        try {
            tickets = new Book_tickets();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        Desktop.add(tickets);
        tickets.setVisible(true);
    }//GEN-LAST:event_book_ticketActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        Report report = null;
        try {
            report = new Report();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        Desktop.add(report);
        report.setVisible(true);
    }//GEN-LAST:event_reportActionPerformed

    private void create_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_accountActionPerformed
        // TODO add your handling code here:
        Create_user account = null;
        try {
            account = new Create_user();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        Desktop.add(account);
        account.setVisible(true);
    }//GEN-LAST:event_create_accountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem add_customer;
    private javax.swing.JMenuItem add_flights;
    private javax.swing.JMenuItem book_ticket;
    private javax.swing.JMenuItem create_account;
    private javax.swing.JMenu customer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem report;
    private javax.swing.JMenuItem search_customer;
    private javax.swing.JMenu tickets;
    private javax.swing.JMenu user;
    // End of variables declaration//GEN-END:variables
}
